/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capaGrafica;

import capaLogica.Status;
import capaLogica.Vehiculo;
import capaPersistencias.PersistenciaVehiculo;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
/**
 *
 * @author RYZEN
 */
public class JFrmActivarDesactivarVehiculo extends javax.swing.JFrame {
ArrayList array = new ArrayList();
    DefaultListModel modelo = new DefaultListModel();
    
    /**
     * Creates new form JFrmActivarDesactivarVehiculo
     */
    public JFrmActivarDesactivarVehiculo() {
        initComponents();
        JLisListaVehiculo.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JLisListaVehiculo = new javax.swing.JList();
        JBtnActivar_Desactivar = new javax.swing.JButton();
        JBtnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Activar o Desactivar Vehiculo");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Lista de Vehiculos");

        jScrollPane1.setViewportView(JLisListaVehiculo);

        JBtnActivar_Desactivar.setText("Activar/Desactivar");
        JBtnActivar_Desactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnActivar_DesactivarActionPerformed(evt);
            }
        });

        JBtnSalir.setText("Salir");
        JBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(JBtnActivar_Desactivar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JBtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBtnActivar_Desactivar)
                    .addComponent(JBtnSalir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnSalirActionPerformed
          this.dispose(); //Instrucción para cerrar la ventana
    }//GEN-LAST:event_JBtnSalirActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
 lista();//llama al metodo lista
    }//GEN-LAST:event_formWindowOpened

    private void JBtnActivar_DesactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnActivar_DesactivarActionPerformed
 int indice = JLisListaVehiculo.getSelectedIndex(); //Variable indice de tipo int que guardará la posición seleccionada
        Status status = null; //Se inicializa una variable de la clase enumerador y se le dará un valor null
        ArrayList<Vehiculo> arrayVehiculo= PersistenciaVehiculo.getArrayVehiculos(); //Se inicializa un arrayList y guardará el arrayList de la clase PersistenciaCliente

        if (indice == -1) { //Si el indice seleccionado es -1, osea no hay nada seleccionado
            JOptionPane.showMessageDialog(this, "Seleccione el cliente que desea Activar/Desactivar"); //Mostrará un mensaje de alerta por medio de un JOptionPane
        } //Se cierra la condición if
        else {
            if (arrayVehiculo.get(indice).getStatus()== status.ACTIVO) { //Condicion que se aplicará Si el status del objeto es ACTIVO
                PersistenciaVehiculo.desactivarVehiculo(indice); //Instrucción para cambiar el status del objeto a INACTIVO
                JOptionPane.showMessageDialog(this, "Se ha desactivado la información del cliente"); //Mensaje de confirmación
                lista(); //Método para llenar o actualizar el jLstClientes
            }  //Se cierra la condicion if
            else {
                PersistenciaVehiculo.activarVehiculo(indice); //Instrucción para cambiar el status del objeto a ACTIVO
                JOptionPane.showMessageDialog(this, "Se ha activado el cliente"); //Mensaje de confirmación
                lista(); //Método para llenar o actualizar el jLstClientes
            } //Se cierra la condicion else
        }    }//GEN-LAST:event_JBtnActivar_DesactivarActionPerformed
 
    public void lista(){// carga el jlist con default model
modelo.removeAllElements();
        for (Vehiculo vehiculo : PersistenciaVehiculo.getArrayVehiculos()) { //foreach -recorre cada celda del arreglo, uno a la vez
        String descripcionVehiculo = vehiculo.getStatus()+" - "+ vehiculo.getIdVehiculo()+" - "+vehiculo.getPrecio()+" - "+vehiculo.getModelo()+"\n";
        modelo.addElement(descripcionVehiculo);
    
                }
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmActivarDesactivarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmActivarDesactivarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmActivarDesactivarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmActivarDesactivarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmActivarDesactivarVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnActivar_Desactivar;
    private javax.swing.JButton JBtnSalir;
    private javax.swing.JList JLisListaVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
