package capaGrafica;

import capaLogica.Status;
import capaLogica.Usuario;
import capaPersistencias.ControlUsuarios;
import capaPersistencias.PersistenciaUsuario;
import javax.swing.JOptionPane; //Se importa la clase JOptionPane


public class jFrmLogueo extends javax.swing.JFrame {
    jFrmRegistrase pantalla;
    int contadorIntentos;
    /**
     * Creates new form jFrmLogueo
     */
    public jFrmLogueo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtUsuario = new javax.swing.JTextField();
        jpwfContrasena = new javax.swing.JPasswordField();
        jbtnIngresar = new javax.swing.JButton();
        jbtnSalir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Usuario: ");

        jLabel2.setText("Password: ");

        jbtnIngresar.setText("Ingresar");
        jbtnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIngresarActionPerformed(evt);
            }
        });

        jbtnSalir.setText("Salir");
        jbtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalirActionPerformed(evt);
            }
        });

        jButton1.setText("Registrarse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtUsuario)
                            .addComponent(jpwfContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnIngresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(jbtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jpwfContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnIngresar)
                    .addComponent(jbtnSalir))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        // Cuando se pierde el foco de la venta verifica si esta en null el objeto pantalla
        // Si esta en null devuelve el foco a la pantalla de logueo
        if(pantalla==null){
            this.requestFocus();
        }
    }//GEN-LAST:event_formWindowLostFocus

    
    private void jbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirActionPerformed
        // Se cierra la aplicacion
        System.exit(0);
    }//GEN-LAST:event_jbtnSalirActionPerformed

    private void jbtnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIngresarActionPerformed
        // Se crea una variable usuario
        Usuario u;
        // Veifica que se haya ingresado un usuario y si no se envia un mensaje de error
        // y devuelve el foco al campo
        if(jtxtUsuario.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Ingrese un usuario");
            jtxtUsuario.requestFocus();
            return;
        }
        
        // Veifica que se haya ingresado una clave y si no se envia un mensaje de error
        // y devuelve el foco al campo
        if(jpwfContrasena.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Ingrese una clave");
            jpwfContrasena.requestFocus();
            return;
        }
        
        // Llama al metodo que busca el usuarios
        u = PersistenciaUsuario.obtenerUsuario(this.jtxtUsuario.getText());
        //si el usuario no se encontro
        if(u == null){
            // Se envia mensaje de error
            JOptionPane.showMessageDialog(this, "El usuario no existe");
            // Se devuelve el foco al campo de usuario
            this.jtxtUsuario.selectAll();
            this.jtxtUsuario.requestFocus();
            // Se incrementa el contador de intentos
            contadorIntentos++;
            // Veirifica si se alcanzo el limite de intentos
            if(contadorIntentos==3){
                //Envia mensaje de error
                JOptionPane.showMessageDialog(this, "Excedio el limite de intentos");
                // se cierra la aplicacion
                System.exit(0);
            }
            return;
        }else{
            // en caso de que el usuario exista verifica que la clave corresponda a la clave guardada
            if(u.getClave().equals(this.jpwfContrasena.getText())){
                // Si corresponse se cierra la ventana de logueo
                this.dispose();
                // Se establece el usuario logueado
                ControlUsuarios.establecerUsuario(u);
                // Se manda a ejecutar la ventana principal
                jFrmPrincipal principal = new jFrmPrincipal();
                principal.setLocationRelativeTo(null);
                principal.setVisible(true);
            }else{
                // En caso de que no coincidan
                // se envia mensaje de error
                JOptionPane.showMessageDialog(this, "La clave es incorrecta");
                this.jpwfContrasena.selectAll();
                // se devuelve el foco al campo de constraseña
                this.jpwfContrasena.requestFocus();
                // se incrementa el contador de intentos
                contadorIntentos++;
                // Se determina si se alcanzo el limite de intentos
                if(contadorIntentos==3){
                    // si se alcanzo se envia mensaje de error
                    JOptionPane.showMessageDialog(this, "Excedio el limite de intentos");
                    // Se cierra la aplicacion
                    //System.exit(0);
                    PersistenciaUsuario.obtenerUsuario(jtxtUsuario.getText()).setStatus(Status.INACTIVO); //Desactiva al usuario si hace más de 3 intentos
                }
                return;
            }
        }
        
    }//GEN-LAST:event_jbtnIngresarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // si se dio click en registrarse se llama a la ventana para registrarse
        pantalla = new jFrmRegistrase();
        pantalla.setLocationRelativeTo(null);
        pantalla.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Cuando se abre la ventana de logueo se inicipaliza el contador de intentos 
        contadorIntentos = 0;
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrmLogueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrmLogueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrmLogueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrmLogueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrmLogueo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbtnIngresar;
    private javax.swing.JButton jbtnSalir;
    private javax.swing.JPasswordField jpwfContrasena;
    private javax.swing.JTextField jtxtUsuario;
    // End of variables declaration//GEN-END:variables
}
