/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capaGrafica;

import capaLogica.TipoVehiculo;
import capaLogica.Vehiculo;
import capaPersistencias.PersistenciaVehiculo;
import java.awt.event.ItemEvent;
import javax.swing.JOptionPane;
/**
 *
 * @author RYZEN
 */
public class JFrmActualizarVehiculo extends javax.swing.JFrame {

    /**
     * Creates new form JFrmActualizarVehiculo
     */
    public JFrmActualizarVehiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JCbxSeleccioneVehículo = new javax.swing.JComboBox<>();
        JTxfModelo = new javax.swing.JTextField();
        JTxfPrecio = new javax.swing.JTextField();
        JCbxTipoVehiculo = new javax.swing.JComboBox<>();
        JBtnGuardar = new javax.swing.JButton();
        JBtnSalir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Actualizar Vehiculo");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel1.setText("Seleccione Vehículo");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel2.setText("Modelo");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel3.setText("Precio");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel4.setText("Tipo De Vehículo");

        JCbxSeleccioneVehículo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JCbxSeleccioneVehículoItemStateChanged(evt);
            }
        });

        JTxfModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxfModeloActionPerformed(evt);
            }
        });

        JTxfPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxfPrecioActionPerformed(evt);
            }
        });

        JBtnGuardar.setText("Guardar");
        JBtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnGuardarActionPerformed(evt);
            }
        });

        JBtnSalir.setText("Salir");
        JBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(JCbxTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JBtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTxfPrecio)
                            .addComponent(JCbxSeleccioneVehículo, 0, 210, Short.MAX_VALUE)
                            .addComponent(JTxfModelo)))
                    .addComponent(jSeparator1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCbxSeleccioneVehículo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTxfModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JTxfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JCbxTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBtnGuardar)
                    .addComponent(JBtnSalir))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnGuardarActionPerformed
        if(JCbxSeleccioneVehículo.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(this, "Seleccione un vehiculo");//despliega un mensaje de error
            JCbxSeleccioneVehículo.requestFocus();//solicita qque lo vuelva a intentar
            return;
        }
        
        if (JTxfModelo.getText().trim().equals("")){ //Se abre condicion if que dará instrucciones en caso de que jTxtDireccion no tenga nada escrito
            JOptionPane.showMessageDialog(this, "Debe digitar el modelo"); //Por medio de un JOptionPane, se mostrará un mensaje de alerta
            JTxfModelo.requestFocus(); //El programa se enfocará en el jTxtDireccion para editarlo
            return; //Se cierra la condición
        }
          if (JTxfPrecio.getText().trim().equals("")){ //Se abre condicion if que dará instrucciones en caso de que jTxtDireccion no tenga nada escrito
            JOptionPane.showMessageDialog(this, "Debe digitar el precio"); //Por medio de un JOptionPane, se mostrará un mensaje de alerta
            JTxfPrecio.requestFocus(); //El programa se enfocará en el jTxtDireccion para editarlo
            return; //Se cierra la condición
        }
          
        try {
            double precio2 = Double.parseDouble(this.JTxfPrecio.getText());// crea la variable 
        } catch (NumberFormatException numberFormatException) {//define el error que quiere atrapar
            JOptionPane.showMessageDialog(this, "El precio no debe tener letras");//confirma el error
            JTxfPrecio.setText("");
            JTxfPrecio.requestFocus();
            JTxfPrecio.selectAll();
            return;
        }
        
        int index = JCbxTipoVehiculo.getSelectedIndex();
        if(index == -1){
            JOptionPane.showMessageDialog(this, "Seleccione el tipo de vehiculo");//despliega un mensaje de error
            JCbxTipoVehiculo.requestFocus();//solicita qque lo vuelva a intentar
            return;
        }
        
        String modelo = JTxfModelo.getText();//otiene los tres datos para la creacion del vehiculo
        double precio= Double.parseDouble(JTxfPrecio.getText());
        TipoVehiculo tipo = (TipoVehiculo) JCbxTipoVehiculo.getSelectedItem();

        int indice =  JCbxSeleccioneVehículo.getSelectedIndex(); //Guarda en una variable indice de tipo int, el indice seleccionado del combo box
        Vehiculo vehiculo= (Vehiculo)JCbxSeleccioneVehículo.getSelectedItem();
        vehiculo.setModelo(modelo);
        vehiculo.setPrecio(precio);
        vehiculo.setTipoVehiculo(tipo);
        
        PersistenciaVehiculo.actualizarVehiculo(indice, vehiculo); //Actualiza el objeto y lo guarda en la clase PersistenciaCliente
        JOptionPane.showMessageDialog(this, "Se ha actualizado!"); //Imprime un mensaje de que la accion se ha realizado con exito
        
        JCbxSeleccioneVehículo.setSelectedIndex(-1);
        JTxfPrecio.setText("");
        JTxfModelo.setText("");
    }//GEN-LAST:event_JBtnGuardarActionPerformed

    private void JBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnSalirActionPerformed
        this.dispose(); //Instrucción para cerrar la ventana
    }//GEN-LAST:event_JBtnSalirActionPerformed

    private void JTxfModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxfModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxfModeloActionPerformed

    private void JTxfPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxfPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxfPrecioActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (Vehiculo vehiculo : PersistenciaVehiculo.getArrayVehiculos()) { //foreach -recorre cada celda del arreglo, uno a la vez
            JCbxSeleccioneVehículo.addItem(vehiculo);//agrega el vehiculo al combo box
        }
        
        for (TipoVehiculo tipoVehiculo : TipoVehiculo.values()) { //foreach -recorre cada celda del arreglo, uno a la vez
            JCbxTipoVehiculo.addItem(tipoVehiculo);
        }
        
        JCbxSeleccioneVehículo.setSelectedIndex(-1);
        this.JTxfModelo.setText("");
        this.JTxfPrecio.setText("");
        JCbxTipoVehiculo.setSelectedIndex(-1);
        
    }//GEN-LAST:event_formWindowOpened

    private void JCbxSeleccioneVehículoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JCbxSeleccioneVehículoItemStateChanged
        try{
            if (evt.getStateChange() == ItemEvent.SELECTED) {
                Vehiculo v = (Vehiculo)JCbxSeleccioneVehículo.getSelectedItem();
                this.JTxfModelo.setText(v.getModelo());
                this.JTxfPrecio.setText(String.valueOf(v.getPrecio()));
                this.JCbxTipoVehiculo.setSelectedItem(v.getTipoVehiculo());
            }
        }
        catch(Exception e){ 
        }
    }//GEN-LAST:event_JCbxSeleccioneVehículoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmActualizarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmActualizarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmActualizarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmActualizarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmActualizarVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnGuardar;
    private javax.swing.JButton JBtnSalir;
    private javax.swing.JComboBox<Vehiculo> JCbxSeleccioneVehículo;
    private javax.swing.JComboBox<TipoVehiculo> JCbxTipoVehiculo;
    private javax.swing.JTextField JTxfModelo;
    private javax.swing.JTextField JTxfPrecio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
