/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capaGrafica;

import capaLogica.Parte;
import capaLogica.Vehiculo;
import capaPersistencias.PersistenciaParte;
import capaPersistencias.PersistenciaVehiculo;
import java.awt.event.ItemEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author RYZEN
 */
public class JFrmModificarParte extends javax.swing.JFrame {

    /**
     * Creates new form JFrmModificarParte
     */
    public JFrmModificarParte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcboParte = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTxaPartesVehiculo = new javax.swing.JTextArea();
        JBtnAgregar = new javax.swing.JButton();
        JBtnBorrar = new javax.swing.JButton();
        JBtnSalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jcboVehiculo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar Partes Vehiculo");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Seleccione el Vehiculo");

        jLabel2.setText("Partes del Vehiculo");

        JTxaPartesVehiculo.setColumns(20);
        JTxaPartesVehiculo.setRows(5);
        jScrollPane1.setViewportView(JTxaPartesVehiculo);

        JBtnAgregar.setText("Agregar");
        JBtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnAgregarActionPerformed(evt);
            }
        });

        JBtnBorrar.setText("Quitar");
        JBtnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnBorrarActionPerformed(evt);
            }
        });

        JBtnSalir.setText("Salir");
        JBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnSalirActionPerformed(evt);
            }
        });

        jLabel3.setText("Seleccione la Parte");

        jcboVehiculo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcboVehiculoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(202, 202, 202))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(jcboVehiculo, 0, 234, Short.MAX_VALUE)
                                .addComponent(jcboParte, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JBtnAgregar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(JBtnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JBtnBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcboVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBtnAgregar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JBtnBorrar))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcboParte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBtnSalir))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {JBtnAgregar, JBtnBorrar, JBtnSalir});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnAgregarActionPerformed
        if(jcboVehiculo.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(this,"Seleccione un vehiculo");
            jcboVehiculo.requestFocus();
            return;
        }
        
        if(jcboParte.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(this,"Seleccione una parte");
            jcboParte.requestFocus();
            return;
        }
        
        Vehiculo v = (Vehiculo)jcboVehiculo.getSelectedItem();
        Parte p = (Parte) jcboParte.getSelectedItem();
        if(v.agregarParte(p)){
            JOptionPane.showMessageDialog(this, "Parte Agregada");
            jcboParte.setSelectedIndex(-1);
            jcboParte.requestFocus();
            cargarDatos();
        }else{
            JOptionPane.showMessageDialog(this, "La parte ya existe en el vehiculo");
            jcboParte.setSelectedIndex(-1);
            jcboParte.requestFocus();
        }
    }//GEN-LAST:event_JBtnAgregarActionPerformed

    private void JBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_JBtnSalirActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (Vehiculo v : PersistenciaVehiculo.getArrayVehiculos()) { 
            jcboVehiculo.addItem(v); 
        } //Se cierra el ciclo for each
        
        for (Parte parte : PersistenciaParte.getArrayPartesActivas()) { //Ciclo for each para llenar el combo box jCboCliente
            jcboParte.addItem(parte); //Se guarda en el jCboCliente el toString del objeto cliente
        } //Se cierra el ciclo for each
        
        jcboVehiculo.setSelectedIndex(-1);
        jcboParte.setSelectedIndex(-1); //Posiciona el jCboCliente en la posición -1 una posicion vacía
        JTxaPartesVehiculo.setText("");
    }//GEN-LAST:event_formWindowOpened

    private void JBtnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnBorrarActionPerformed
        if(jcboVehiculo.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(this,"Seleccione un vehiculo");
            jcboVehiculo.requestFocus();
            return;
        }
        
        if(jcboParte.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(this,"Seleccione una parte");
            jcboParte.requestFocus();
            return;
        }
        
        Vehiculo v = (Vehiculo)jcboVehiculo.getSelectedItem();
        Parte p = (Parte) jcboParte.getSelectedItem();
        if(v.eliminarParte(p)){
            JOptionPane.showMessageDialog(this, "Parte Eliminada");
            jcboParte.setSelectedIndex(-1);
            jcboParte.requestFocus();
            cargarDatos();
        }else{
            JOptionPane.showMessageDialog(this, "La parte no existe en el vehiculo");
            jcboParte.setSelectedIndex(-1);
            jcboParte.requestFocus();
        }
    }//GEN-LAST:event_JBtnBorrarActionPerformed

    private void jcboVehiculoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcboVehiculoItemStateChanged
        try{
            if (evt.getStateChange() == ItemEvent.SELECTED) {
                cargarDatos();
            }
        }
        catch(Exception e){ 
        }
    }//GEN-LAST:event_jcboVehiculoItemStateChanged

    private void cargarDatos(){
        String hilera = "";
        Vehiculo v = (Vehiculo)jcboVehiculo.getSelectedItem();
        for(Parte p:v.getArrayPartes()){
            hilera += p.toString()+"\n";
        }
        this.JTxaPartesVehiculo.setText(hilera);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmModificarParte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmModificarParte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmModificarParte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmModificarParte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmModificarParte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnAgregar;
    private javax.swing.JButton JBtnBorrar;
    private javax.swing.JButton JBtnSalir;
    private javax.swing.JTextArea JTxaPartesVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<Parte> jcboParte;
    private javax.swing.JComboBox<Vehiculo> jcboVehiculo;
    // End of variables declaration//GEN-END:variables
}
