/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capaGrafica;

import capaPersistencias.PersistenciaVehiculo;

/**
 *
 * @author RYZEN
 */
public class JFrmMantenimientoVehiculo extends javax.swing.JFrame {

    /**
     * Creates new form JFrmMantenimientoVehiculos
     */
    public JFrmMantenimientoVehiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTxaVehiculosGuardados = new javax.swing.JTextArea();
        JBtnSalir = new javax.swing.JButton();
        JBtnActiva_DesactivaVehiculo = new javax.swing.JButton();
        JBtnActualizarVehiculo = new javax.swing.JButton();
        JBtnAgregarVehiculo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mantenimiento de Vehiculos");
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        JTxaVehiculosGuardados.setColumns(20);
        JTxaVehiculosGuardados.setRows(5);
        jScrollPane1.setViewportView(JTxaVehiculosGuardados);

        JBtnSalir.setText("Salir");
        JBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnSalirActionPerformed(evt);
            }
        });

        JBtnActiva_DesactivaVehiculo.setText("Activa/Desactiva Vehiculo");
        JBtnActiva_DesactivaVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnActiva_DesactivaVehiculoActionPerformed(evt);
            }
        });

        JBtnActualizarVehiculo.setText("Actualizar Vehiculo");
        JBtnActualizarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnActualizarVehiculoActionPerformed(evt);
            }
        });

        JBtnAgregarVehiculo.setText("Agregar Vehiculo");
        JBtnAgregarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnAgregarVehiculoActionPerformed(evt);
            }
        });

        jButton1.setText("Agregar/ Modificar Parte");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JBtnActualizarVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBtnAgregarVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBtnActiva_DesactivaVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBtnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {JBtnActiva_DesactivaVehiculo, JBtnActualizarVehiculo, JBtnAgregarVehiculo, JBtnSalir});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JBtnAgregarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JBtnActualizarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JBtnActiva_DesactivaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(26, 26, 26)
                        .addComponent(JBtnSalir)
                        .addGap(0, 296, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {JBtnActiva_DesactivaVehiculo, JBtnActualizarVehiculo, JBtnAgregarVehiculo, JBtnSalir});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        JTxaVehiculosGuardados.setText(PersistenciaVehiculo.listaVehiculos());//presenta la lista de vehiculos guardados
    }//GEN-LAST:event_formWindowOpened

    private void JBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnSalirActionPerformed
        this.dispose(); //Instrucción para cerrar la ventana
    }//GEN-LAST:event_JBtnSalirActionPerformed

    private void JBtnAgregarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnAgregarVehiculoActionPerformed
        JFrmAgregarVehiculo AgregaVehiculo = new JFrmAgregarVehiculo();//crea la ventana para agreagar vehiculos    
        AgregaVehiculo.setVisible(true);// la hace visible
        AgregaVehiculo.setLocationRelativeTo(this);//la coloca en el centro
    }//GEN-LAST:event_JBtnAgregarVehiculoActionPerformed

    private void JBtnActualizarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnActualizarVehiculoActionPerformed
        JFrmActualizarVehiculo ActualizaVehiculo = new JFrmActualizarVehiculo();//crea la ventana para actualizar vehiculos    
        ActualizaVehiculo.setVisible(true);// la hace visible
        ActualizaVehiculo.setLocationRelativeTo(this);//la coloca en el centro
    }//GEN-LAST:event_JBtnActualizarVehiculoActionPerformed

    private void JBtnActiva_DesactivaVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnActiva_DesactivaVehiculoActionPerformed
        JFrmActivarDesactivarVehiculo activa_desactiva = new JFrmActivarDesactivarVehiculo();//crea la ventana para activar y desactivar vehiculos    
        activa_desactiva.setVisible(true);// la hace visible
        activa_desactiva.setLocationRelativeTo(this);//la coloca en el centro
    }//GEN-LAST:event_JBtnActiva_DesactivaVehiculoActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        JTxaVehiculosGuardados.setText(PersistenciaVehiculo.listaVehiculos());//presenta la lista de vehiculos guardados
    }//GEN-LAST:event_formWindowGainedFocus

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFrmModificarParte modificar = new JFrmModificarParte();//crea la ventana para activar y desactivar vehiculos    
        modificar.setVisible(true);// la hace visible
        modificar.setLocationRelativeTo(this);//la coloca en el centro
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmMantenimientoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmMantenimientoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmMantenimientoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmMantenimientoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmMantenimientoVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnActiva_DesactivaVehiculo;
    private javax.swing.JButton JBtnActualizarVehiculo;
    private javax.swing.JButton JBtnAgregarVehiculo;
    private javax.swing.JButton JBtnSalir;
    private javax.swing.JTextArea JTxaVehiculosGuardados;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
