/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capaGrafica;


import capaLogica.Usuario;
import capaLogica.TipoUsuario;
import capaPersistencias.ControlUsuarios;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
//import javafx.scene.paint.Color;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;

/**
 *
 * @author anchi
 */
public class jFrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form jFrmPrincipal
     */
    FondoPanel fondo = new FondoPanel();
    public Usuario u;
    
    public jFrmPrincipal() {
        initComponents();
        this.setContentPane(fondo);      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMnbMenu = new javax.swing.JMenuBar();
        jMnuArchivo = new javax.swing.JMenu();
        BtnCerrarSesion = new javax.swing.JMenuItem();
        jMnuSalir = new javax.swing.JMenuItem();
        jMnuMantenimiento = new javax.swing.JMenu();
        jMniClientes = new javax.swing.JMenuItem();
        jMniPaises = new javax.swing.JMenuItem();
        jMniPartes = new javax.swing.JMenuItem();
        jMniUsuarios = new javax.swing.JMenuItem();
        jMniVehiculos = new javax.swing.JMenuItem();
        jMnuFacturacion = new javax.swing.JMenu();
        jMniFacturar = new javax.swing.JMenuItem();
        jMnuPersonalizacion = new javax.swing.JMenu();
        jMniCrear = new javax.swing.JMenuItem();
        jMnuReportes = new javax.swing.JMenu();
        jMeniReporteVehiculos = new javax.swing.JMenuItem();
        jMniReporteVehiculosTipo = new javax.swing.JMenuItem();
        jMniReportePartes = new javax.swing.JMenuItem();
        jMniReporteFacturas = new javax.swing.JMenuItem();
        jMniReporteFacturasCliente = new javax.swing.JMenuItem();
        jMniReporteClientes = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de personalización de autos");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jMnbMenu.setBorder(null);

        jMnuArchivo.setText("Archivo");

        BtnCerrarSesion.setText("Cerrar Sesion");
        BtnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarSesionActionPerformed(evt);
            }
        });
        jMnuArchivo.add(BtnCerrarSesion);

        jMnuSalir.setText("Salir");
        jMnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuSalirActionPerformed(evt);
            }
        });
        jMnuArchivo.add(jMnuSalir);

        jMnbMenu.add(jMnuArchivo);

        jMnuMantenimiento.setText("Mantenimiento");

        jMniClientes.setText("Clientes");
        jMniClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniClientesActionPerformed(evt);
            }
        });
        jMnuMantenimiento.add(jMniClientes);

        jMniPaises.setText("Paises");
        jMniPaises.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniPaisesActionPerformed(evt);
            }
        });
        jMnuMantenimiento.add(jMniPaises);

        jMniPartes.setText("Partes");
        jMniPartes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniPartesActionPerformed(evt);
            }
        });
        jMnuMantenimiento.add(jMniPartes);

        jMniUsuarios.setText("Usuarios");
        jMniUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniUsuariosActionPerformed(evt);
            }
        });
        jMnuMantenimiento.add(jMniUsuarios);

        jMniVehiculos.setText("Vehiculos");
        jMniVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniVehiculosActionPerformed(evt);
            }
        });
        jMnuMantenimiento.add(jMniVehiculos);

        jMnbMenu.add(jMnuMantenimiento);

        jMnuFacturacion.setText("Facturación");
        jMnuFacturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuFacturacionActionPerformed(evt);
            }
        });

        jMniFacturar.setText("Facturar");
        jMniFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniFacturarActionPerformed(evt);
            }
        });
        jMnuFacturacion.add(jMniFacturar);

        jMnbMenu.add(jMnuFacturacion);

        jMnuPersonalizacion.setText("Personalización");
        jMnuPersonalizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuPersonalizacionActionPerformed(evt);
            }
        });

        jMniCrear.setText("Crear");
        jMniCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniCrearActionPerformed(evt);
            }
        });
        jMnuPersonalizacion.add(jMniCrear);

        jMnbMenu.add(jMnuPersonalizacion);

        jMnuReportes.setText("Reportes");

        jMeniReporteVehiculos.setText("Vehiculos");
        jMeniReporteVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMeniReporteVehiculosActionPerformed(evt);
            }
        });
        jMnuReportes.add(jMeniReporteVehiculos);

        jMniReporteVehiculosTipo.setText("Vehiculos por TIpo");
        jMniReporteVehiculosTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniReporteVehiculosTipoActionPerformed(evt);
            }
        });
        jMnuReportes.add(jMniReporteVehiculosTipo);

        jMniReportePartes.setText("Partes");
        jMniReportePartes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniReportePartesActionPerformed(evt);
            }
        });
        jMnuReportes.add(jMniReportePartes);

        jMniReporteFacturas.setText("Facturas");
        jMniReporteFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniReporteFacturasActionPerformed(evt);
            }
        });
        jMnuReportes.add(jMniReporteFacturas);

        jMniReporteFacturasCliente.setText("Facturas por Tipo Cliente");
        jMniReporteFacturasCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniReporteFacturasClienteActionPerformed(evt);
            }
        });
        jMnuReportes.add(jMniReporteFacturasCliente);

        jMniReporteClientes.setText("Clientes");
        jMniReporteClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniReporteClientesActionPerformed(evt);
            }
        });
        jMnuReportes.add(jMniReporteClientes);

        jMnbMenu.add(jMnuReportes);

        setJMenuBar(jMnbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 403, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Cuando se abre la ventana se obtiene el usuario logueado
        Usuario usuario = ControlUsuarios.obtenerUsuario();
        // se llama al metodo que agrega el status bar
        agregarStatusBar(usuario);
        // se llama al metodo que activa y desactiva las opciones de menu
        activarMenus(usuario);
        // se establece la ventana en estado maximizado
        this.setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void activarMenus(Usuario u){
        //Verifica si el usuario logueado es tipo regular
        if(u.getTipoUsuario() == TipoUsuario.REGULAR){
            // Se desactivan las opciones del menu correspondientes
            this.jMnuFacturacion.setVisible(false);
            this.jMniReporteFacturas.setVisible(false);
            this.jMniReporteFacturasCliente.setVisible(false);
            this.jMniReporteClientes.setVisible(false);
            this.jMnuMantenimiento.setVisible(false);
        }else if(u.getTipoUsuario() == TipoUsuario.VENDEDOR){// Verifica si el usuario logueado es vendedor
            // se desactiva las opciones de mantenimiento
            this.jMnuMantenimiento.setVisible(false);
        }
    }
    
    // Metodo que agrega el status bar
    private void agregarStatusBar(Usuario u){
        // CRea una variable panel para el status bar
        JPanel statusBar = new JPanel(new FlowLayout(FlowLayout.LEFT));
        // establece el tipo de borde del panel
        statusBar.setBorder(new CompoundBorder(new LineBorder(java.awt.Color.DARK_GRAY),
            new EmptyBorder(4, 4, 4, 4)));
        // Crea un nuevo label
        final JLabel status = new JLabel();
        // Agrega la informacion del usuario logueado al label
        status.setText(u.getUsuario() + " - " + u.getNombre());
        // Agrega el label al panel
        statusBar.add(status);
        
        // Establece la ubicacion del status bar y la agrega el formulario principal
        this.setLayout(new BorderLayout());
        this.add(statusBar, BorderLayout.SOUTH);
    }
    
    private void jMniUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniUsuariosActionPerformed
        // Despliega el formulario Mantenimiento Usuarios
        jFrmMantenimientoUsuarios pantalla = new jFrmMantenimientoUsuarios();
        pantalla.setLocationRelativeTo(null);
        pantalla.setVisible(true);
    }//GEN-LAST:event_jMniUsuariosActionPerformed

    private void jMnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuSalirActionPerformed
        //Cierra la aplicacion
        System.exit(0);
    }//GEN-LAST:event_jMnuSalirActionPerformed

    private void jMnuPersonalizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuPersonalizacionActionPerformed
        
    }//GEN-LAST:event_jMnuPersonalizacionActionPerformed

    private void jMniCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniCrearActionPerformed
        // Despliega el formulario crear personalizcion
        jFrmPersonalizacion pantalla = new jFrmPersonalizacion();
        pantalla.setLocationRelativeTo(null);
        pantalla.setVisible(true);
    }//GEN-LAST:event_jMniCrearActionPerformed

    private void jMniClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniClientesActionPerformed
        // Despliega el formulario Mantenimiento Clientes
        jFrmMantenimientoCliente pantalla = new jFrmMantenimientoCliente();
        pantalla.setLocationRelativeTo(null);
        pantalla.setVisible(true);
    }//GEN-LAST:event_jMniClientesActionPerformed

    private void jMniPaisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniPaisesActionPerformed
        // Despliega el formulario Mantenimiento paises
        jFrmMantenimientoPais pantalla = new jFrmMantenimientoPais();
        pantalla.setLocationRelativeTo(null);
        pantalla.setVisible(true);
    }//GEN-LAST:event_jMniPaisesActionPerformed

    private void jMnuFacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuFacturacionActionPerformed
        
    }//GEN-LAST:event_jMnuFacturacionActionPerformed

    private void jMniFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniFacturarActionPerformed
        // Despliega el formulario de facturacion
        jFrmFacturacion pantalla = new jFrmFacturacion();
        pantalla.setLocationRelativeTo(null);
        pantalla.setVisible(true);
    }//GEN-LAST:event_jMniFacturarActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus

    }//GEN-LAST:event_formWindowGainedFocus

    private void jMniVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniVehiculosActionPerformed
        // Despliega el formulario Mantenimiento Vehiculos
        JFrmMantenimientoVehiculo pantalla = new JFrmMantenimientoVehiculo();
        pantalla.setLocationRelativeTo(null);
        pantalla.setVisible(true);
    }//GEN-LAST:event_jMniVehiculosActionPerformed
    
    private void jMniPartesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniPartesActionPerformed
        // Despliega el formulario Mantenimiento partes
        jFrmMantenimientoPartes pantalla = new jFrmMantenimientoPartes();
        pantalla.setLocationRelativeTo(null);
        pantalla.setVisible(true);
    }//GEN-LAST:event_jMniPartesActionPerformed

    private void jMeniReporteVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMeniReporteVehiculosActionPerformed
        // Despliega el formulario Reporte de vehiculos
        jFrmReportVehiculos pantalla = new jFrmReportVehiculos();
        pantalla.setLocationRelativeTo(null);
        pantalla.setVisible(true);
    }//GEN-LAST:event_jMeniReporteVehiculosActionPerformed

    private void jMniReporteVehiculosTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniReporteVehiculosTipoActionPerformed
        // Despliega el formulario Reporte de vehiculos por tipo
        jFrmReportVehiculosTipo pantalla = new jFrmReportVehiculosTipo();
        pantalla.setLocationRelativeTo(null);
        pantalla.setVisible(true);
    }//GEN-LAST:event_jMniReporteVehiculosTipoActionPerformed

    private void jMniReportePartesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniReportePartesActionPerformed
        // Despliega el formulario Reporte de partes
        jFrmReportePartes pantalla = new jFrmReportePartes();
        pantalla.setLocationRelativeTo(null);
        pantalla.setVisible(true);
    }//GEN-LAST:event_jMniReportePartesActionPerformed

    private void jMniReporteFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniReporteFacturasActionPerformed
        // Despliega el formulario Reporte de factura
        jFrmReporteFacturas pantalla = new jFrmReporteFacturas();
        pantalla.setLocationRelativeTo(null);
        pantalla.setVisible(true);
    }//GEN-LAST:event_jMniReporteFacturasActionPerformed

    private void jMniReporteFacturasClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniReporteFacturasClienteActionPerformed
        // Despliega el formulario Reporte de facturas por tipo de cliente
        jFrmReporteFacturasCliente pantalla = new jFrmReporteFacturasCliente();
        pantalla.setLocationRelativeTo(null);
        pantalla.setVisible(true);
    }//GEN-LAST:event_jMniReporteFacturasClienteActionPerformed

    private void jMniReporteClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniReporteClientesActionPerformed
        // Despliega el formulario Reporte de clientes
        jFrmReporteClientes pantalla = new jFrmReporteClientes();
        pantalla.setLocationRelativeTo(null);
        pantalla.setVisible(true);
    }//GEN-LAST:event_jMniReporteClientesActionPerformed

    private void BtnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarSesionActionPerformed
        this.dispose();
        jFrmLogueo ventana = new jFrmLogueo();
        ventana.setVisible(true);
        ventana.setLocationRelativeTo(null);
    }//GEN-LAST:event_BtnCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new jFrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BtnCerrarSesion;
    private javax.swing.JMenuItem jMeniReporteVehiculos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuBar jMnbMenu;
    private javax.swing.JMenuItem jMniClientes;
    private javax.swing.JMenuItem jMniCrear;
    private javax.swing.JMenuItem jMniFacturar;
    private javax.swing.JMenuItem jMniPaises;
    private javax.swing.JMenuItem jMniPartes;
    private javax.swing.JMenuItem jMniReporteClientes;
    private javax.swing.JMenuItem jMniReporteFacturas;
    private javax.swing.JMenuItem jMniReporteFacturasCliente;
    private javax.swing.JMenuItem jMniReportePartes;
    private javax.swing.JMenuItem jMniReporteVehiculosTipo;
    private javax.swing.JMenuItem jMniUsuarios;
    private javax.swing.JMenuItem jMniVehiculos;
    private javax.swing.JMenu jMnuArchivo;
    private javax.swing.JMenu jMnuFacturacion;
    private javax.swing.JMenu jMnuMantenimiento;
    private javax.swing.JMenu jMnuPersonalizacion;
    private javax.swing.JMenu jMnuReportes;
    private javax.swing.JMenuItem jMnuSalir;
    // End of variables declaration//GEN-END:variables

    class FondoPanel extends JPanel{
        private Image imagen;
        
        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/imagenes/fondoBMW.jpg")).getImage();
            g.drawImage(imagen,0,0,getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
}
