
package capaGrafica;

import capaLogica.Cliente;
import capaLogica.Factura;
import capaLogica.Parte;
import capaLogica.TipoFactura;
import capaLogica.TipoVehiculo;
import capaLogica.Vehiculo;
import capaPersistencias.PersistenciaCliente;
import capaPersistencias.PersistenciaFactura;
import capaPersistencias.PersistenciaParte;
import capaPersistencias.PersistenciaVehiculo;
import java.awt.event.ItemEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author anchi
 */
public class jFrmFacturacion extends javax.swing.JFrame {
    // Se define una variable de tipo personalizacion
    Factura f;
    
    /**
     * Creates new form jFrmPersonalizaion
     */
    public jFrmFacturacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlVehiculo = new javax.swing.JPanel();
        jcboVehiculo = new javax.swing.JComboBox<>();
        jcboTipoVehiculo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPnlVehiculo1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jcboParte = new javax.swing.JComboBox<>();
        jbtnAgregar = new javax.swing.JButton();
        jbtnQuitar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxaDetalles = new javax.swing.JTextArea();
        jbtnSalir = new javax.swing.JButton();
        jPnlVehiculo2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jcboCliente = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jcboTipoFactura = new javax.swing.JComboBox<>();
        jbtnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Facturación");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPnlVehiculo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Selección de Vehículo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jcboVehiculo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcboVehiculoItemStateChanged(evt);
            }
        });

        jcboTipoVehiculo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcboTipoVehiculoItemStateChanged(evt);
            }
        });

        jLabel1.setText("Tipo de Vehiculo:");

        jLabel2.setText("Vehiculos:");

        javax.swing.GroupLayout jPnlVehiculoLayout = new javax.swing.GroupLayout(jPnlVehiculo);
        jPnlVehiculo.setLayout(jPnlVehiculoLayout);
        jPnlVehiculoLayout.setHorizontalGroup(
            jPnlVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlVehiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcboTipoVehiculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcboVehiculo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPnlVehiculoLayout.setVerticalGroup(
            jPnlVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlVehiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcboTipoVehiculo))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPnlVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcboVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        jPnlVehiculo1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Selección de Partes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel3.setText("Parte:");

        jbtnAgregar.setText("Agregar");
        jbtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAgregarActionPerformed(evt);
            }
        });

        jbtnQuitar.setText("Quitar");
        jbtnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnQuitarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnlVehiculo1Layout = new javax.swing.GroupLayout(jPnlVehiculo1);
        jPnlVehiculo1.setLayout(jPnlVehiculo1Layout);
        jPnlVehiculo1Layout.setHorizontalGroup(
            jPnlVehiculo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlVehiculo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcboParte, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jbtnAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPnlVehiculo1Layout.setVerticalGroup(
            jPnlVehiculo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlVehiculo1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlVehiculo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcboParte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnAgregar)
                    .addComponent(jbtnQuitar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Detalles de Personalización", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jtxaDetalles.setEditable(false);
        jtxaDetalles.setColumns(20);
        jtxaDetalles.setRows(5);
        jScrollPane1.setViewportView(jtxaDetalles);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addContainerGap())
        );

        jbtnSalir.setText("Salir");
        jbtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalirActionPerformed(evt);
            }
        });

        jPnlVehiculo2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Selección de Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel4.setText("Cliente:");

        jcboCliente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcboClienteItemStateChanged(evt);
            }
        });
        jcboCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jcboClienteFocusLost(evt);
            }
        });

        jLabel5.setText("Tipo factura:");

        jcboTipoFactura.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcboTipoFacturaItemStateChanged(evt);
            }
        });
        jcboTipoFactura.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jcboTipoFacturaFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPnlVehiculo2Layout = new javax.swing.GroupLayout(jPnlVehiculo2);
        jPnlVehiculo2.setLayout(jPnlVehiculo2Layout);
        jPnlVehiculo2Layout.setHorizontalGroup(
            jPnlVehiculo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlVehiculo2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlVehiculo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlVehiculo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcboCliente, 0, 165, Short.MAX_VALUE)
                    .addComponent(jcboTipoFactura, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnlVehiculo2Layout.setVerticalGroup(
            jPnlVehiculo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlVehiculo2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlVehiculo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPnlVehiculo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcboTipoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jbtnGuardar.setText("Guardar y Salir");
        jbtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPnlVehiculo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbtnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPnlVehiculo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPnlVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPnlVehiculo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPnlVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPnlVehiculo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSalir)
                    .addComponent(jbtnGuardar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //Llama al metodo que carga los valores en los combo box
        cargarCombos();
        
        // Reinicia las selecciones de los combo box
        jcboCliente.setSelectedIndex(-1);
        jcboTipoFactura.setSelectedIndex(-1);
                   
        // Limpia las selecciones del combo boxtipo vehiculo
        jcboTipoVehiculo.setSelectedIndex(-1);
        
        // Remueve todos los items del combo box vehiculo
        jcboVehiculo.removeAllItems();
        
        //Limpia el text area que despliega los detalles de la personalizacion
        jtxaDetalles.setText("");
    }//GEN-LAST:event_formWindowOpened

    private void jcboTipoVehiculoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcboTipoVehiculoItemStateChanged
        // maneja el evento de cambios en la seleccion del combo box de TipoVehiculo
        try{   
            // verifica si el evento disparado es una selecccion
            if (evt.getStateChange() == ItemEvent.SELECTED) {
                // Crea una instancia TipoVehiculo 
                // y le asigna el tipo seleccionada
                TipoVehiculo tipo  = (TipoVehiculo)jcboTipoVehiculo.getSelectedItem();
                // Limpia el combo box de vehiculos
                jcboVehiculo.removeAllItems();
                // Itera un arreglo que devuelve los vehiculos del tipo seleccionado
                for(Vehiculo v:PersistenciaVehiculo.getArrayVehiculos(tipo)){
                    // agrega el objeto vehiculo al combo box vehiculo
                    jcboVehiculo.addItem(v);
                }
                // reinicia la seleccion del combo box vehiculo
                jcboVehiculo.setSelectedIndex(-1);
                // Limpia el text area que despliega los detalles de la personalizacion
                jtxaDetalles.setText("");
            }
        }
        catch(Exception e){ 
        }
    }//GEN-LAST:event_jcboTipoVehiculoItemStateChanged

    private void jcboVehiculoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcboVehiculoItemStateChanged
        // maneja el evento de cambios en la seleccion del combo box de vehiculos
        try{   
            // verifica si el evento disparado es una selecccion
            if (evt.getStateChange() == ItemEvent.SELECTED) {
                // guarda en una variable cliente el cliente seleccionado en el 
                //combo box
                Cliente c = (Cliente)jcboCliente.getSelectedItem();
                
                // guarda en una variable Tipofactura el Tipofactura seleccionado en el 
                //combo box
                TipoFactura tf = (TipoFactura)jcboTipoFactura.getSelectedItem();
                
                // guarda en una variable vehiculo el vehiculo seleccionado en el 
                //combo box
                Vehiculo v = (Vehiculo)jcboVehiculo.getSelectedItem();
                
                // Crea un nuevo objeto personalizacion pasando como 
                // parametro el vehiculo seleecionado
                f = new Factura(c,v,tf);
                
                // Despliega los detalles de l personalizacion en el text area
                jtxaDetalles.setText(f.toString());
                
                // Remueve todos los items del combo box parte
                jcboParte.removeAllItems();
                
                // Se itera a traves de las partes y se agregan al combo box de partes
                for (Parte parte:PersistenciaParte.getArrayPartesExtras(v)){
                    jcboParte.addItem(parte);
                }
                
                // reinicia la seleccion del combo box parte
                jcboParte.setSelectedIndex(-1);
            }
        }
        catch(Exception e){ 
        }
    }//GEN-LAST:event_jcboVehiculoItemStateChanged

    private void jbtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAgregarActionPerformed
        // Obtiene el index seleccionado en el combo box de vehiculo
        int index = jcboVehiculo.getSelectedIndex();
        // Verifica si el indice de seleccion corresponde a no haber 
        // seleccionado nada
        if(index == -1){
            // Despliega mensaje de error solicitando una seleccion
            JOptionPane.showMessageDialog(this, "Seleccione un vehículo");
            return;
        }else{// En caso de haber una seleccion valida
            // obtiene el indice de la seleccion del combox box de parte
            index = jcboParte.getSelectedIndex();
            // Verifica si el indice de seleccion corresponde a no haber 
            // seleccionado nada
            if(index == -1){
                // Despliega mensaje de error solicitando una seleccion
                JOptionPane.showMessageDialog(this, "Seleccione una parte");
                return;
            }else{
                // Guarada en un variable parte la partes seleccionado en el combo box
                Parte parte = (Parte)jcboParte.getSelectedItem();
                // Agrega la parte a la personalizacion
                if(f.agregarExtra(parte)){
                    // Cuando fue exitoso refresca la informacion en el text area
                    // que muestra los detalles de la personalizacion
                    jtxaDetalles.setText(f.toString());
                    jcboParte.setSelectedIndex(-1);
                }else{
                    // Despliega mensaje de error indicando que no se pudo eliminar la parte
                    JOptionPane.showMessageDialog(this, "La parte ya ha sido agregada");
                }
            }
        }
    }//GEN-LAST:event_jbtnAgregarActionPerformed

    private void jbtnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnQuitarActionPerformed
        // obtiene el indice de la seleccion del combox box de parte
        int index = jcboParte.getSelectedIndex();
        // Verifica si el indice de seleccion corresponde a no haber 
        // seleccionado nada
        if(index == -1){
            // Despliega mensaje de error solicitando una seleccion
            JOptionPane.showMessageDialog(this, "Seleccione una parte");
            return;
        }else{
            // Guarada en un variable parte la partes seleccionado en el combo box
            Parte parte = (Parte)jcboParte.getSelectedItem();
            // llama el metodo que elimina partes de la personalizacion
            // retorna verdadero en caso de exito y false en caso de fallo
            if(f.eliminarParte(parte)){
                // Cuando fue exitoso refresca la informacion en el text area
                // que muestra los detalles de la personalizacion
                jtxaDetalles.setText(f.toString());
            }else{
                // Despliega mensaje de error indicando que no se pudo eliminar la parte
                JOptionPane.showMessageDialog(this, "La parte seleccionada no ha sido agregada");
            }        
        }
    }//GEN-LAST:event_jbtnQuitarActionPerformed

    private void jcboClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcboClienteFocusLost
        // Obtiene el index seleccionado en el combo box de cliente
        int index = jcboCliente.getSelectedIndex();
        // Verifica si el indice de seleccion corresponde a no haber 
        // seleccionado nada
        if(index == -1){
            // Despliega mensaje de error solicitando una seleccion
            JOptionPane.showMessageDialog(this, "Seleccione un cliente");
            jcboCliente.requestFocus();
            return;
        }        
    }//GEN-LAST:event_jcboClienteFocusLost

    private void jcboTipoFacturaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcboTipoFacturaFocusLost
        // Obtiene el index seleccionado en el combo box de tipo de factura
        int index = jcboTipoFactura.getSelectedIndex();
        // Verifica si el indice de seleccion corresponde a no haber 
        // seleccionado nada
        if(index == -1){
            // Despliega mensaje de error solicitando una seleccion
            JOptionPane.showMessageDialog(this, "Seleccione el tipo de factura");
            jcboTipoFactura.requestFocus();
            return;
        }
    }//GEN-LAST:event_jcboTipoFacturaFocusLost

    private void jcboClienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcboClienteItemStateChanged
        // maneja el evento de cambios en la seleccion del combo box de vehiculos
        try{   
            // verifica si el evento disparado es una selecccion
            if (evt.getStateChange() == ItemEvent.SELECTED) {
                // Obtiene el index seleccionado en el combo box de tipo de factura
                int index = jcboVehiculo.getSelectedIndex();

                // guarda en una variable vehiculo el cliente seleccionado en el 
                //combo box
                Cliente c = (Cliente)jcboCliente.getSelectedItem();
                
                //Verica que se haya selccionado el vehiculo
                if(index!=-1){
                    // se estblece el nuevo cliente
                    f.setCliente(c);
                    
                    // Despliega los detalles de la factura en el text area
                    jtxaDetalles.setText(f.toString());
                }
            }
        }
        catch(Exception e){ 
        }
    }//GEN-LAST:event_jcboClienteItemStateChanged

    private void jcboTipoFacturaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcboTipoFacturaItemStateChanged
        // maneja el evento de cambios en la seleccion del combo box de vehiculos
        try{   
            // verifica si el evento disparado es una selecccion
            if (evt.getStateChange() == ItemEvent.SELECTED) {
                // Obtiene el index seleccionado en el combo box de tipo de factura
                int index = jcboVehiculo.getSelectedIndex();

                // guarda en una variable vehiculo el cliente seleccionado en el 
                //combo box
                TipoFactura tf = (TipoFactura)jcboTipoFactura.getSelectedItem();
                
                //Verica que se haya selccionado el vehiculo
                if(index!=-1){
                    // se estblece el nuevo cliente
                    f.setTipoFactura(tf);
                    
                    // Despliega los detalles de la factura en el text area
                    jtxaDetalles.setText(f.toString());
                }
            }
        }
        catch(Exception e){ 
        }
    }//GEN-LAST:event_jcboTipoFacturaItemStateChanged

    private void jbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtnSalirActionPerformed

    private void jbtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGuardarActionPerformed
        if(!jtxaDetalles.getText().equals("")){
            PersistenciaFactura.agregarFactura(f);
            this.dispose();
        }
    }//GEN-LAST:event_jbtnGuardarActionPerformed

    private void cargarCombos(){
        // Se itera a traves de los tipos de los clientes y se agregan al combo box
        for (Cliente c:PersistenciaCliente.getArrayClientesActivos()){
            jcboCliente.addItem(c);
        }
        
        // Se itera a traves de los tipos de vehiculo y se agregan al combo box
        // tipo vehiculo
        for (TipoVehiculo tipoVehiculo:TipoVehiculo.values()){
            jcboTipoVehiculo.addItem(tipoVehiculo);
        }
        
        // Se itera a traves de los tipos de factura y se agregan al combo box
        for (TipoFactura tipoFactura:TipoFactura.values()){
            this.jcboTipoFactura.addItem(tipoFactura);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrmFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrmFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrmFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrmFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrmFacturacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPnlVehiculo;
    private javax.swing.JPanel jPnlVehiculo1;
    private javax.swing.JPanel jPnlVehiculo2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnAgregar;
    private javax.swing.JButton jbtnGuardar;
    private javax.swing.JButton jbtnQuitar;
    private javax.swing.JButton jbtnSalir;
    private javax.swing.JComboBox<Cliente> jcboCliente;
    private javax.swing.JComboBox<Parte> jcboParte;
    private javax.swing.JComboBox<TipoFactura> jcboTipoFactura;
    private javax.swing.JComboBox<TipoVehiculo> jcboTipoVehiculo;
    private javax.swing.JComboBox<Vehiculo> jcboVehiculo;
    private javax.swing.JTextArea jtxaDetalles;
    // End of variables declaration//GEN-END:variables
}
