/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capaGrafica;

import javax.swing.JOptionPane;
import capaLogica.TipoVehiculo;
import capaLogica.Vehiculo;
import capaPersistencias.PersistenciaVehiculo;

/**
 *
 * @author RYZEN
 */
public class JFrmAgregarVehiculo extends javax.swing.JFrame {

    /**
     * Creates new form JFrmAgregarVehiculos
     */
    public JFrmAgregarVehiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JTxfModelo = new javax.swing.JTextField();
        JTxfPrecio = new javax.swing.JTextField();
        JCbxTipoVehiculo = new javax.swing.JComboBox<>();
        JBtnGuardar = new javax.swing.JButton();
        JBtnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Vehiculo");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel2.setText("Modelo");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel3.setText("Precio");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel4.setText("Tipo Vehículo");

        JCbxTipoVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCbxTipoVehiculoActionPerformed(evt);
            }
        });

        JBtnGuardar.setText("Guardar");
        JBtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnGuardarActionPerformed(evt);
            }
        });

        JBtnSalir.setText("Salir");
        JBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JCbxTipoVehiculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JTxfPrecio)
                            .addComponent(JTxfModelo)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JBtnGuardar)
                        .addGap(152, 152, 152)
                        .addComponent(JBtnSalir)))
                .addGap(0, 13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTxfModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JTxfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JCbxTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBtnGuardar)
                    .addComponent(JBtnSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JCbxTipoVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCbxTipoVehiculoActionPerformed


    }//GEN-LAST:event_JCbxTipoVehiculoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (TipoVehiculo tipoVehiculo : TipoVehiculo.values()) { //foreach -recorre cada celda del arreglo, uno a la vez
            JCbxTipoVehiculo.addItem(tipoVehiculo);
        }
        JCbxTipoVehiculo.setSelectedIndex(-1);
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void JBtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnGuardarActionPerformed

        if (JTxfModelo.getText().trim().equals("")) { //Se abre condicion if que dará instrucciones en caso de que jTxtDireccion no tenga nada escrito
            JOptionPane.showMessageDialog(this, "Debe digitar el modelo"); //Por medio de un JOptionPane, se mostrará un mensaje de alerta
            JTxfModelo.requestFocus(); //El programa se enfocará en el jTxtDireccion para editarlo
            return;
        } //Se cierra la condición

        if (JTxfPrecio.getText().trim().equals("")) { //Se abre condicion if que dará instrucciones en caso de que jTxtDireccion no tenga nada escrito
            JOptionPane.showMessageDialog(this, "Debe digitar el precio"); //Por medio de un JOptionPane, se mostrará un mensaje de alerta
            JTxfPrecio.requestFocus(); //El programa se enfocará en el jTxtDireccion para editarlo
            return;
        } //Se cierra la condición
        try {
            Double precio2 = Double.parseDouble(JTxfPrecio.getText());//obtiene el precio

        } catch (NumberFormatException numberFormatException) {//define el error que quiere atrapar
            JOptionPane.showMessageDialog(this, "El precio no debe tener letras");//despliega un mensaje de error
            JTxfPrecio.requestFocus();//solicita qque lo vuelva a intentar
            JTxfPrecio.selectAll();
            return;
        }

        int index = JCbxTipoVehiculo.getSelectedIndex();
        if(index == -1){
            JOptionPane.showMessageDialog(this, "Seleccione el tipo de vehiculo");//despliega un mensaje de error
            JCbxTipoVehiculo.requestFocus();//solicita qque lo vuelva a intentar
            return;
        }
        
        Double precio = Double.parseDouble(JTxfPrecio.getText());
        String modelo = JTxfModelo.getText();
        TipoVehiculo tipoVehiculo = (TipoVehiculo) JCbxTipoVehiculo.getSelectedItem();//hasta aqui recoge los datos

        Vehiculo vehiculo = new Vehiculo(modelo, precio, tipoVehiculo);//construye el objeto

        PersistenciaVehiculo.agregarVehiculo(vehiculo);
        JOptionPane.showMessageDialog(this, "Se ha Agregado con Exito!");//confirma la insercion
        JTxfPrecio.setText("");//limpia los campos
        JTxfModelo.setText("");
        JCbxTipoVehiculo.setSelectedIndex(-1);
    }//GEN-LAST:event_JBtnGuardarActionPerformed

    private void JBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnSalirActionPerformed
        this.dispose(); //Instrucción para cerrar la ventana
    }//GEN-LAST:event_JBtnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmAgregarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmAgregarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmAgregarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmAgregarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JFrmAgregarVehiculo().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnGuardar;
    private javax.swing.JButton JBtnSalir;
    private javax.swing.JComboBox<TipoVehiculo> JCbxTipoVehiculo;
    private javax.swing.JTextField JTxfModelo;
    private javax.swing.JTextField JTxfPrecio;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
